exclude: |
  (?x)(
      ^superpack/|
      ^private/
      )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: "whiskermenu-1.rc"
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-json
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
        exclude: "linux\/config\/autostart\/.*"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(json|yaml|yml|markdown|md)$

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: remove-crlf

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint-fix

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-4
    hooks:
      - id: shfmt
        args: [-w, -s, -ci, -bn, -i, "2"]

  - repo: local
    hooks:
      - id: save-guake-settings
        name: save-guake-settings
        description: Dumps Guake settings from dconf to file in repo (Linux only)
        language: script
        entry: ./linux/dconf-guake-hook.py
        pass_filenames: false
        always_run: true
      - id: save-xfce-settings
        name: save-xfce-settings
        description: Copies xfce4 settings to repo
        language: script
        entry: ./linux/xfce-settings-hook.py
        pass_filenames: false
        always_run: true
      - id: PSScriptAnalyzer
        name: PSScriptAnalyzer
        description: Run PSScriptAnalyzer on commit
        entry: ./common/powershell/Invoke-PSSAPreCommitHook.ps1
        language: script
        pass_filenames: false
