version: 2.1

jobs:
  pre-commit-checks:
    machine:
      image: "windows-server-2022-gui:current"
    resource_class: windows.medium
    steps:
      - checkout
      - run:
          name: Make sure CRLFs were not added by git
          shell: powershell.exe
          command: |
            $ErrorActionPreference = "Stop"
            git config --global core.autocrlf input
            git rm -rf --cached .
            git reset --hard HEAD
      - run:
          name: Install dependencies
          shell: powershell.exe
          command: |
            $ErrorActionPreference = "Stop"
            Install-Module -Name PSScriptAnalyzer -Force
            pip install pre-commit
      - run:
          name: Run pre-commit checks
          shell: powershell.exe
          command: |
            $ErrorActionPreference = "Stop"
            pre-commit run --show-diff-on-failure --all-files

workflows:
  circle-ci-tests:
    jobs:
      - pre-commit-checks
