version: 2.1

jobs:
  pre-commit-checks:
    machine:
      image: 'windows-server-2022-gui:current'
    resource_class: windows.medium
    steps:
      - checkout
      - run:
          name: Make sure CRLFs were not added by git
          shell: powershell.exe
          command: |
            $ErrorActionPreference = "Stop"
            git config --global core.autocrlf input
            git rm -rf --cached .
            git reset --hard HEAD
      - run:
          name: Install dependencies
          shell: powershell.exe
          command: |
            $ErrorActionPreference = "Stop"
            Install-Module -Name PSScriptAnalyzer -Force
            pip install pre-commit
      - run:
          name: Run pre-commit checks
          shell: powershell.exe
          command: |
            $ErrorActionPreference = "Stop"
            $merge_base = git merge-base -a HEAD origin/master
            Write-Output "Merge base: $merge_base"
            $changed_files = git diff --name-only $merge_base`...HEAD
            Write-Output "Changed files since branched from origin/master: $changed_files"
            git reset --soft $merge_base
            pre-commit run --show-diff-on-failure --files $changed_files

workflows:
  circle-ci-tests:
    jobs:
      - pre-commit-checks
