version: 2.1

jobs:
  pre-commit-checks:
    docker:
      - image: cimg/python:3.10.7
    steps:
      - checkout
      - run:
          name: Install pre-commit
          command: |
            pip install pre-commit
      - run:
          name: Run pre-commit hooks
          command: |
            merge_base=$(git merge-base -a HEAD origin/master)
            changed_files=$(git diff --name-only $merge_base...HEAD)
            echo "Changed files since branched from origin/master: " $changed_files
            git reset --soft $merge_base
            pre-commit run --show-diff-on-failure --files $changed_files
  powershell-checks:
    machine:
      image: 'windows-server-2022-gui:current'
    resource_class: windows.medium
    steps:
      - checkout
      - run:
          name: Install ScriptAnalyzer module
          command: |
            Install-Module -Name PSScriptAnalyzer -Force
      - run: |
          name: Check PS scripts
          command: |
            .\win10-only\Invoke-PSSAPreCommitHook.ps1


workflows:
  circle-ci-tests:
    jobs:
      - pre-commit-checks
      - powershell-checks
